---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::r-base=4.2.1
  - conda-forge::r-ggplot2=3.4.4
  - conda-forge::r-reshape2=1.4.4
