---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - zhangzhen-cpl::octave-statistics=1.7.4
  - conda-forge::python=3.10