---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::python=3.10
  - conda-forge::numpy=1.23.5
  - conda-forge::pandas=2.0.3
  - conda-forge::scipy=1.10.1
